DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'DWASA_USERS'
      AND COLUMN_NAME = 'CREATED_BY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DWASA_USERS ADD (CREATED_BY NUMBER(19))';
    END IF;
END;
/

UPDATE DWASA_USERS
SET ROOT_ID = ID
WHERE ROOT_ID IS NULL OR ROOT_ID <> ID;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'DWASA_USERS'
      AND COLUMN_NAME = 'ROOT_ID'
      AND NULLABLE = 'Y';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DWASA_USERS MODIFY (ROOT_ID NUMBER(19) NOT NULL)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'DWASA_USERS'
      AND CONSTRAINT_NAME = 'UK_DWASA_USERS_ROOT_ID';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DWASA_USERS ADD CONSTRAINT UK_DWASA_USERS_ROOT_ID UNIQUE (ROOT_ID)';
    END IF;
END;
/
