DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'DWASA_USERS'
      AND COLUMN_NAME = 'UPDATED_BY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DWASA_USERS ADD (UPDATED_BY NUMBER(19))';
    END IF;
END;
/
