BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE WASTAGE ADD SECTION_ID NUMBER(19)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE WASTAGE ADD CONSTRAINT FK_WASTAGE_SECTION FOREIGN KEY (SECTION_ID) REFERENCES SECTION (ID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2275, -955) THEN
            RAISE;
        END IF;
END;
/
