spring.application.name=DWASA_Backend


spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=bwtp
spring.datasource.password=wasa123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

app.jwt.secret=015bcb872aa134e63e5e97c1fcb3fda1444a0c1b52cc9d8c16d22cdfd200b787456326eb51b00031189a77e831f22a3fbcbf982c05ef9d880b7b7fa518ca4f19
app.jwt.expiration-seconds=86400
